let listaCompletaDeDatos = [
    { "id": 1, "word": "吃", "pinyin": "chī", "meaning": "eat" },
    { "id": 2, "word": "饭", "pinyin": "fàn", "meaning": "food or rice" },
    { "id": 3, "word": "吃饭", "pinyin": "chīfàn", "meaning": "to eat" },
    { "id": 4, "word": "吃苹果", "pinyin": "chī píngguǒ", "meaning": "eat apples" },
    { "id": 5, "word": "睡觉", "pinyin": "shuìjiào", "meaning": "to sleep" },
    { "id": 6, "word": "学习", "pinyin": "xuéxí", "meaning": "to study" },
    { "id": 7, "word": "工作", "pinyin": "gōngzuò", "meaning": "to work" },
    { "id": 8, "word": "上厕所", "pinyin": "shàng cèsuǒ", "meaning": "to use the bathroom" },
    { "id": 9, "word": "买东西", "pinyin": "mǎi dōngxī", "meaning": "to buy things  go shopping" },
    { "id": 10, "word": "买书", "pinyin": "mǎishū", "meaning": "to buy books" },
    { "id": 11, "word": "买", "pinyin": "mǎi", "meaning": "to buy" },
    { "id": 12, "word": "东西", "pinyin": "dōngxī", "meaning": "things" },
    { "id": 13, "word": "看书", "pinyin": "kànshū", "meaning": "read books" },
    { "id": 14, "word": "看", "pinyin": "kàn", "meaning": "to look, to see, to watch... actions with eyes" },
    { "id": 15, "word": "早饭", "pinyin": "zǎofàn", "meaning": "breakfast" },
    { "id": 16, "word": "晚饭", "pinyin": "wǎnfàn", "meaning": "dinner" },
    { "id": 17, "word": "喝咖啡", "pinyin": "hē kāfēi", "meaning": "to drink coffee." },
    { "id": 18, "word": "水", "pinyin": "shuǐ", "meaning": "water" },
    { "id": 19, "word": "喝水", "pinyin": "hē shuǐ", "meaning": "to drink water" },
    { "id": 20, "word": "觉", "pinyin": "jué", "meaning": "sleep (noun)" },
    { "id": 21, "word": "回", "pinyin": "huí", "meaning": "to go back" },
    { "id": 22, "word": "来", "pinyin": "lái", "meaning": "to come to" }
];