// let lesson1_vocab_indiceMax = 34;
let listaCompletaDeDatos = [
    { "id": 1, "word": "高兴", "pinyin": "gāoxìng", "meaning": "happy" },
    { "id": 2, "word": "国", "pinyin": "guó", "meaning": "country; state; nation" },
    { "id": 3, "word": "很", "pinyin": "hěn", "meaning": "very" },
    { "id": 4, "word": "叫", "pinyin": "jiào", "meaning": "call; be called" },
    { "id": 5, "word": "名字", "pinyin": "míngzi", "meaning": "Name" },
    { "id": 6, "word": "哪", "pinyin": "nǎ", "meaning": "which" },
    { "id": 7, "word": "哪里", "pinyin": "nǎ lǐ", "meaning": "where" },
    { "id": 8, "word": "你", "pinyin": "nǐ", "meaning": "you" },
    { "id": 9, "word": "人", "pinyin": "rén", "meaning": "people" },
    { "id": 10, "word": "认识", "pinyin": "rènshi", "meaning": "know" },
    { "id": 11, "word": "什么", "pinyin": "shénme", "meaning": "What" },
    { "id": 12, "word": "岁", "pinyin": "suì", "meaning": "year, age" },
    { "id": 13, "word": "他", "pinyin": "tā", "meaning": "he" },
    { "id": 14, "word": "她", "pinyin": "tā", "meaning": "she" },
    { "id": 15, "word": "晚上", "pinyin": "wǎnshang", "meaning": "Night" },
    { "id": 16, "word": "我", "pinyin": "wǒ", "meaning": "I" },
    { "id": 17, "word": "也", "pinyin": "yě", "meaning": "also" },
    { "id": 18, "word": "好", "pinyin": "hǎo", "meaning": "good" },
    { "id": 19, "word": "再见", "pinyin": "zàijiàn", "meaning": "Bye" },
    { "id": 20, "word": "多", "pinyin": "duō", "meaning": "many; much; more" },
    { "id": 21, "word": "大", "pinyin": "dà", "meaning": "large, big" },
    { "id": 22, "word": "了", "pinyin": "le", "meaning": "past tense marker" },
    { "id": 23, "word": "是", "pinyin": "shì", "meaning": "yes" },
    { "id": 24, "word": "喜欢", "pinyin": "xǐhuan", "meaning": "like" },
    { "id": 25, "word": "不", "pinyin": "bù", "meaning": "No" },
    { "id": 26, "word": "早上", "pinyin": "zǎoshang", "meaning": "Morning" },
    { "id": 27, "word": "美国", "pinyin": "měi guó", "meaning": "USA" },
    { "id": 28, "word": "英国", "pinyin": "yīng guó", "meaning": "the UK" },
    { "id": 29, "word": "法国", "pinyin": "fǎ guó", "meaning": "France" },
    { "id": 30, "word": "德国", "pinyin": "dé guó", "meaning": "Germany" },
    { "id": 31, "word": "西班牙", "pinyin": "xī bān yá", "meaning": "Spain" },
    { "id": 32, "word": "日本", "pinyin": "rì běn", "meaning": "Japan" },
    { "id": 33, "word": "泰国", "pinyin": "tài guó", "meaning": "Thailand" },
    { "id": 34, "word": "危地马拉", "pinyin": "wēi dì mǎ lā", "meaning": "Guatemala" }
];

