let listaCompletaDeDatos = [
    { "id": 1, "word": "个", "pinyin": "gè", "meaning": "measure word for people, most objects that have a clear shape, places and most things..." },
    { "id": 2, "word": "本", "pinyin": "běn", "meaning": "measure word for things that look like books" },
    { "id": 3, "word": "张", "pinyin": "zhāng", "meaning": "measure word for flat objects (most of the time made of wood)" },
    { "id": 4, "word": "两", "pinyin": "liǎng", "meaning": "\"two\" when used with a measure word." },
    { "id": 5, "word": "词典", "pinyin": "cídiǎn", "meaning": "dictionary" },
    { "id": 6, "word": "词", "pinyin": "cí", "meaning": "word" },
    { "id": 7, "word": "典", "pinyin": "diǎn", "meaning": "thick book" },
    { "id": 8, "word": "桌子", "pinyin": "zhuōzi", "meaning": "desk or table" },
    { "id": 9, "word": "椅子", "pinyin": "yǐzi", "meaning": "chair" },
    { "id": 10, "word": "床", "pinyin": "chuáng", "meaning": "bed" },
    { "id": 11, "word": "纸", "pinyin": "zhǐ", "meaning": "paper" },
    { "id": 12, "word": "台", "pinyin": "tái", "meaning": "measure word for electronic devices" },
    { "id": 13, "word": "电视", "pinyin": "diànshì", "meaning": "tv" },
    { "id": 14, "word": "冰箱", "pinyin": "bīngxiāng", "meaning": "fridge" },
    { "id": 15, "word": "一个人", "pinyin": "yīgè rén", "meaning": "one person" },
    { "id": 16, "word": "两个鸡蛋", "pinyin": "liǎng gè jīdàn", "meaning": "two eggs" },
    { "id": 17, "word": "三个商店", "pinyin": "sān gè shāngdiàn", "meaning": "three stores" },
    { "id": 18, "word": "四个苹果", "pinyin": "sì gè píngguǒ", "meaning": "four apples" },
    { "id": 19, "word": "五个朋友", "pinyin": "wǔ gè péngyǒu", "meaning": "five friends" },
    { "id": 20, "word": "六个学校", "pinyin": "liù gè xuéxiào", "meaning": "six schools" },
    { "id": 21, "word": "七本书", "pinyin": "qī běn shū", "meaning": "seven books" },
    { "id": 22, "word": "八本本子", "pinyin": "bā běnběn zi", "meaning": "eight notebooks" },
    { "id": 23, "word": "九本词典", "pinyin": "jiǔ běn cídiǎn", "meaning": "nine dictionaries" },
    { "id": 24, "word": "一张桌子", "pinyin": "yī zhāng zhuōzi", "meaning": "one desk" },
    { "id": 25, "word": "两张椅子", "pinyin": "liǎng zhāng yǐzi", "meaning": "two chairs" },
    { "id": 26, "word": "三张床", "pinyin": "sān zhāng chuáng", "meaning": "three beds" },
    { "id": 27, "word": "四张纸", "pinyin": "sì zhāng zhǐ", "meaning": "four sheets of paper" },
    { "id": 28, "word": "上", "pinyin": "Shàng", "meaning": "on top of / above" },
    { "id": 29, "word": "下", "pinyin": "xià", "meaning": "under something" },
    { "id": 30, "word": "桌子下", "pinyin": "zhuōzi xià", "meaning": "under the table" },
    { "id": 31, "word": "房间", "pinyin": "fángjiān", "meaning": "room" },
    { "id": 32, "word": "房间里", "pinyin": "fángjiān lǐ", "meaning": "inside a room" },
    { "id": 33, "word": "里", "pinyin": "lǐ", "meaning": "inside" },
    { "id": 34, "word": "外", "pinyin": "wài", "meaning": "outside" },
    { "id": 35, "word": "房间外", "pinyin": "fángjiān wài", "meaning": "outside of the room" },
    { "id": 36, "word": "老人", "pinyin": "lǎorén", "meaning": "old person" },
    { "id": 37, "word": "只", "pinyin": "zhǐ", "meaning": "measure word for small animals" },
    { "id": 38, "word": "辆", "pinyin": "liàng", "meaning": "measure word for vehicles" },
    { "id": 39, "word": "支", "pinyin": "zhī", "meaning": "measure word for stick-like things" },
    { "id": 40, "word": "作业", "pinyin": "zuòyè", "meaning": "homework" },
    { "id": 41, "word": "家庭办公室", "pinyin": "jiātíng bàngōngshì", "meaning": "home office" },
    { "id": 42, "word": "或者", "pinyin": "huòzhě", "meaning": "or" },
];